log using mindist_hs_match.log, replace
/* This do file reads in data taken from a GIS process. Briefly, the data is generated by geocoding school addresses for 
jurisdictions in the sample (with school codes and street addresses taken from the ELSEGIS_1970 file) and then finding the 
school within the minimum distance from each tract in the border sample. This data includes each tract in the sample, paired 
to the nearest school. The OE number for the school district and for the school itself will help us match this data to the OCR 
information on racial composition.*/

clear 
set mem 30m
/* This (first round of) GIS data was collected by Dave Van Riper at U Minnesota in 2005*/
insheet using ~/Tract_block/OCR_school/Dave_2005/high_mindist_120505.txt, tab
/* This round was collected by Matt Baird at UCLA in Summer 2008*/
append using high_mindist_2008.dta
/* Both of these tract files contains state, county and tract codes as well as oenum and oeschool of nearest HS*/
/* First merge with racial composition data at the school level for 1970*/
sort oenum oeschool
merge oenum oeschool using OCR_school1970_matt.dta
/* Test merge of geocoded tracts with OCR data*/
tab _merge
rename _merge _merge1
/* These jurisdictions with only one HS were not included in the GIS process. No need to find nearest HS because all (public 
school) students in the district would attend the same HS*/
tab jurcode if count==1
/* Prepare to merge with block data*/
rename state_text statefip
rename county_tex county
rename tract_1 tract1
sort statefip county tract1
merge statefip county tract1 using ~/Tract_block/1970/block_1970_aej.dta
tab _merge
tab jurcode if count==1
count

/* For jurisdictions with 1 HS, assign black % of that one HS to all tracts*/
sort jurcode
quietly by jurcode: egen count_hs=max(count)
label var count_hs "# of hs in jurisdiction"
quietly by jurcode: egen temp=max(perenr_black)
replace perenr_black=temp if count_hs==1
/* Dearborn didn't match (for some reason?), but all high schools are 0% black*/
replace perenr_black=0 if jurcode=="dearbomi"

/* Keep high schools that are the only high school in a jurisdiction (count==1) or high schools that matched with one or more 
tracts as being the geographically closest one (_merge1==3)*/
*keep if count_hs==1 | _merge1==3
drop count temp _merge

/* Drop small places*/
#delimit ;
gen temp=(jurcode=="braddopa" | jurcode=="easpitpa" | jurcode=="edgewopa" | jurcode=="homestpa" | jurcode=="inghrapa" | 
jurcode=="mouolipa" | jurcode=="munhalpa" | jurcode=="norbrapa" | jurcode=="oxnardca" | jurcode=="porhueca" |  
jurcode=="porvuepa" | jurcode=="rankinpa" | jurcode=="turcrepa" | jurcode=="wallpa" | jurcode=="weshompa" | 
jurcode=="whitakpa" | jurcode=="wilmerpa" | jurcode=="floparny");
#delimit cr
sort borderno
by borderno: egen temp1=max(temp)
tab jurcode if temp1==1
drop if temp1==1
/* Drop borders in same school district (LA Unified)*/
drop if borderno>=317 & borderno<=319
/* Some districts have no OCR data. Create a variable that indicates 'no_ocr" as a jurisdiction attribute*/
sort borderno jurcode
by borderno jurcode: egen minocr=min(no_ocrdata)
count if jurcode=="bevhilca"
count

/* % black enroll should be a border-by-jurcode variable*/
sort borderno jurcode
by borderno jurcode: egen perenr_black1=mean(perenr_black)
by borderno jurcode: egen disths1=mean(distance)
by borderno jurcode: egen perenr_elem=mean(perblack)
label var disths1 "mean distance to nearest HS"
label var perenr_black1 "% black enroll, HS from OCR, border-jurcode"
label var perenr_elem "guess from mean% black on block in border-jurcode"
gen lndisths=ln(disths1)
gen lnavval=ln(av_value)
gen peryoung=(per04+per59)
gen perold=(per1013+per1417)
save block_1970_withhs_aej.dta, replace
log close

